
start: task_type_decl* task mission

task_type_decl: TASK_TYPE_KW task_type LBRACE task_type_body RBRACE
task_type_body: ID

task: TASK_KW LBRACE task_decl* RBRACE
task_decl: task_type task_name task_body
task_body: LBRACE [attributes (COMMA attributes)*] RBRACE
attributes: attribute
attribute: ID COLON attribute_expr

attribute_expr: NUMBER
              | name
              | LSQUA [paren_tuple (COMMA paren_tuple)*] RSQUA
              | LANGL name RANGL
              | paren_tuple

paren_tuple: LPAREN NUMBER COMMA NUMBER COMMA NUMBER RPAREN

task_type: TASK_DETECT_KW
         | TASK_TRACK_KW
         | TASK_AVOID_KW
         | TASK_TEST_KW
         | name

task_name: name
name: ID

mission: MISSION_KW LBRACE mission_content RBRACE
mission_content: mission_start_decl mission_transition*
mission_start_decl: MISSION_START_KW task_name
mission_transition: TRANSITION_KW LPAREN cond RPAREN task_name ARROW task_name
cond: ID (LPAREN (NUMBER | ID) RPAREN)?


%import common.WS
%ignore WS

NUMBER: /-?\d+(\.\d+)?/
ID: /[α-ωa-zA-Z_][α-ωa-zA-Z0-9_'-]*/

TASK_TYPE_KW: "TaskTypeKw"
TASK_KW: "Task"
MISSION_KW: "Mission"
TRANSITION_KW: "Transition"
MISSION_START_KW: "Start"
TASK_DETECT_KW: "Detect"
TASK_TRACK_KW: "Track"
TASK_AVOID_KW: "Avoid"
TASK_TEST_KW: "Test"

LBRACE: "{"
RBRACE: "}"
LPAREN: "("
RPAREN: ")"
LSQUA: "["
RSQUA: "]"
COMMA: ","
COLON: ":"
ARROW: "->"
LANGL: "<"
RANGL: ">"